[package]
name = "llm_grpc"
version = "0.1.0"
edition = "2024"

[dependencies]
llm_calls = { path = "../llm_calls" }

tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
tonic = "0.13"
prost = "0.13"

[build-dependencies]
tonic-build = "0.13"
