[package]
name = "llm_http"
version = "0.1.0"
edition = "2024"

[dependencies]
llm_calls = { path = "../llm_calls" }

tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
axum = "0.8"
serde = { version = "1", features = ["derive"] }
